version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["bundle", "exec", "rails", "server", "-p", "3000", "-b", "0.0.0.0"]
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  postgres:
